### ISSUE TITLE
Fix: Add support for PGPPBEEncryptedData block type

### ISSUE THREAD

**Issue by skarpushin** [pgptool/pgptool#162]
User reported an issue while trying to decrypt gpg file. Log:

```
java.lang.RuntimeException: This file doesn't look like encrypted file OR format is not supported
	at org.pgptool.gui.encryption.implpgp.EncryptionServicePgpImpl.findKeyIdsForDecryption(EncryptionServicePgpImpl.java:289)
	at org.pgptool.gui.encryption.implpgp.EncryptionServicePgpImpl.findKeyIdsForDecryption(EncryptionServicePgpImpl.java:257)
	at org.pgptool.gui.ui.decryptone.DecryptOnePm$4.propertyChange(DecryptOnePm.java:322)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at ru.skarpushin.swingpm.modelprops.ModelProperty.firePropertyChanged(ModelProperty.java:118)
	at ru.skarpushin.swingpm.modelprops.ModelProperty.setValueByOwner(ModelProperty.java:74)
	at org.pgptool.gui.ui.decryptone.DecryptOnePm$2.handleFileWasChosen(DecryptOnePm.java:270)
	at org.pgptool.gui.ui.tools.browsefs.ExistingFileChooserDialog.askUserForFile(ExistingFileChooserDialog.java:59)
	at org.pgptool.gui.ui.decryptone.DecryptOnePm.init(DecryptOnePm.java:158)
	at org.pgptool.gui.ui.decryptonedialog.DecryptOneDialogPm.init(DecryptOneDialogPm.java:49)
	at org.pgptool.gui.ui.root.RootPm$DecryptionWindowOpener.postConstructPm(RootPm.java:614)
	at org.pgptool.gui.ui.root.RootPm$DialogOpener.openWindow(RootPm.java:745)
	at org.pgptool.gui.ui.root.RootPm$DialogOpener$1.actionPerformed(RootPm.java:726)
	at org.pgptool.gui.ui.mainframe.MainFrameView$5.actionPerformed(MainFrameView.java:226)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassCastException: org.bouncycastle.openpgp.PGPPBEEncryptedData cannot be cast to org.bouncycastle.openpgp.PGPPublicKeyEncryptedData
	at org.pgptool.gui.encryption.implpgp.EncryptionServicePgpImpl.findKeyIdsForDecryption(EncryptionServicePgpImpl.java:280)
```

**Comment by skarpushin** [comment]
As it turns out, such exception happens when one tried to decrypt file encrypted using symmetrical algorithm, instead of PGP key. 
Technically, I could implement this, but it will require substantial re-architecture of the application. I don't see why I would do that especially taking the fact that symmetric encryption is done WITHOUT usage of PGP keys.
