### ISSUE TITLE
Hotfix: file decryption crashes in some cases for very large files

### ISSUE THREAD

**Issue by andriy-svirskyy** [pgptool/pgptool#221]
Version 0.5.9.0 crashes decrypting the file with error 

> Failed to decrypt file -> java.lang.ArithmeticException: BigInteger divide by zero -> BigInteger divide by zero
>  [ PGP Tool v0.5.9.0, Java v1.8.0_242 ]

The same file can be successfully decrypted with version 0.5.4.0

![failure](https://user-images.githubusercontent.com/17915706/74679951-26339080-51b7-11ea-88c5-1b5f206fab74.png)
![success](https://user-images.githubusercontent.com/17915706/74679952-2764bd80-51b7-11ea-9a11-620d0deb9cd0.png)

**Comment by skarpushin** [comment]
@andriy-svirskyy , thanks for the report. Can you please email me log file sergey.v.karpushin@gmail.com? It is located in your home folder, file name is `pgptool-gui.log`. In case you're not comfortable sharing whole file (it will contain file names and key names), please cut & paste exception stack trace for the same error. 
Exception stack-trace looks something like 

```
org.pgptool.gui.app.GenericException: error.failedToCheckForNewVersions
	at org.pgptool.gui.autoupdate.impl.NewVersionCheckerGitHubImpl.findNewUpdateIfAvailable(NewVersionCheckerGitHubImpl.java:79)
	at org.pgptool.gui.ui.checkForUpdates.CheckForUpdatesPm$1.run(CheckForUpdatesPm.java:87)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: HTTP request failed: https://api.github.com/repos/pgptool/pgptool/releases/latest
	at org.pgptool.gui.tools.HttpTools.httpGet(HttpTools.java:59)
	at org.pgptool.gui.autoupdate.impl.NewVersionCheckerGitHubImpl.findNewUpdateIfAvailable(NewVersionCheckerGitHubImpl.java:61)
	... 2 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at org.pgptool.gui.tools.HttpTools.httpGet(HttpTools.java:44)
	... 3 more

```

**Comment by andriy-svirskyy** [comment]
@skarpushin Emailed you directly log file as requested.

**Comment by skarpushin** [comment]
@andriy-svirskyy , thank you very much! I'll be publishing fix for this issue relatively soon. Somehow progress bar logic was messed up.

**Comment by skarpushin** [comment]
@andriy-svirskyy , I've published new version which supposed to have this bug fixed. I wasn't able to reproduce it on my own. Please let me know if this bug fixed for you. 
New version was uploaded here: https://github.com/pgptool/pgptool/releases/tag/0.5.9.1

**Comment by andriy-svirskyy** [comment]
@skarpushin , I've tested with the same file and can confirm that issue is gone.

Thank you for support!
