### ISSUE TITLE
Fix: Subsequent text decryption with cached password must not crash

### ISSUE THREAD

**Issue by KZFlyer** [pgptool/pgptool#244]
![PGPTool Error](https://user-images.githubusercontent.com/39107717/99318867-8a62ae00-2836-11eb-82c3-f7c163119a50.png)

When using Paste and Decrypt from the Clipboard the following error occurs. It decrypts the text with no issues.

Failed to open window getkeypassworddialogpm -> internal application error (NPE) [ PGP Tool v0.5.9.2, Java v1.8.0_261 ]

**Comment by skarpushin** [comment]
@KZFlyer sorry, somehow notification regarding this issue "slipped through the cracks". Can you please provide logs?

**Comment by KZFlyer** [comment]
No problem. I think I only removed my information (placed a string of 9's where my info was), but let me know if I got rid of something important. 

[11.16.20 error log.txt](https://github.com/pgptool/pgptool/files/5826285/11.16.20.error.log.txt)

**Comment by skarpushin** [comment]
@KZFlyer thank you.
Just copy-pasting most interesting part here:
```
java.lang.NullPointerException
	at org.pgptool.gui.ui.root.RootPm$DialogOpener.openWindow(RootPm.java:837)
	at org.pgptool.gui.ui.root.RootPm$DialogOpener$1.actionPerformed(RootPm.java:812)
	at org.pgptool.gui.ui.root.RootPm$5$DecryptTextHostImpl.askUserForKeyAndPassword(RootPm.java:525)
	at org.pgptool.gui.ui.decrypttext.DecryptTextPm.decrypt(DecryptTextPm.java:198)
	at org.pgptool.gui.ui.decrypttext.DecryptTextPm.access$1500(DecryptTextPm.java:63)
	at org.pgptool.gui.ui.decrypttext.DecryptTextPm$6.actionPerformed(DecryptTextPm.java:309)

```

**Comment by skarpushin** [comment]
**STR**:
1. Open app and any decrypt file
2. Encrypt text for same recipient which was used for decrypting file
3. Attempt to decrypt this text
4. (issue) Observe NPE
